const SPACE_STORE='wuli_housemate_spaces_v3',LEGACY_STORE='wuli_housemate_v1';
const spaceCollections=['expenses','chores','items','rules'];
let world=null,storageLocked=false;
function validWorld(w){return w?.version===3&&Array.isArray(w.people)&&w.people.length>0&&w.people.every(p=>typeof p.id==='string'&&typeof p.name==='string')&&Array.isArray(w.spaces)&&w.spaces.every(s=>typeof s.id==='string'&&typeof s.name==='string'&&Array.isArray(s.memberIds)&&spaceCollections.every(k=>Array.isArray(s[k])))}
function newSpaceData(name,ownerId){return {id:crypto.randomUUID(),name,ownerId,memberIds:[ownerId],createdAt:new Date().toISOString(),archived:false,inviteToken:crypto.randomUUID(),activity:[],expenses:[],chores:[],items:[],rules:[]}}
function loadHousehold(seed){
  try{const raw=localStorage.getItem(SPACE_STORE);if(raw){const parsed=JSON.parse(raw);if(!validWorld(parsed))throw Error('Invalid space data');world=parsed;return projectSpace()}}
  catch{storageLocked=true}
  let old;try{const raw=localStorage.getItem(LEGACY_STORE);old=raw?JSON.parse(raw):structuredClone(seed);if(raw&&!localStorage.getItem('wuli_housemate_backup_before_spaces_v1'))localStorage.setItem('wuli_housemate_backup_before_spaces_v1',raw)}catch{old=structuredClone(seed);storageLocked=true}
  if(old?.version!==1||!Array.isArray(old.people)||!old.people.length||!spaceCollections.every(k=>Array.isArray(old[k]))){storageLocked=true;old=structuredClone(seed)}
  old=migrateData(old);
  const room=newSpaceData('春和里 · 6 栋',old.people[0].id);room.memberIds=old.people.map(p=>p.id);for(const k of spaceCollections)room[k]=old[k];
  world={version:3,people:old.people,activeUserId:old.currentUser,activeSpaceId:room.id,spaces:[room],preferences:{theme:'journal',motionEnabled:old.motionEnabled!==false,roomLit:old.roomLit===true}};
  return projectSpace();
}
function joinedSpaces(id=world.activeUserId){return world.spaces.filter(s=>!s.archived&&s.memberIds.includes(id))}
function projectSpace(){
  if(!world.people.some(p=>p.id===world.activeUserId))world.activeUserId=world.people[0].id;
  let room=joinedSpaces().find(s=>s.id===world.activeSpaceId)||joinedSpaces()[0];world.activeSpaceId=room?.id||null;
  const result={version:1,schemaVersion:2,spaceId:room?.id||null,people:world.people,currentUser:world.activeUserId,motionEnabled:world.preferences?.motionEnabled!==false,roomLit:world.preferences?.roomLit===true};
  for(const k of spaceCollections)result[k]=room?.[k]||[];return result;
}
function persistWorld(){if(storageLocked){toast('旧数据读取异常，已保留原文。本次临时体验不会覆盖它。');return false}try{localStorage.setItem(SPACE_STORE,JSON.stringify(world));return true}catch{toast('浏览器存储不足，请在演示设置中导出备份');return false}}
function saveHousehold(s){
  const room=world.spaces.find(r=>r.id===s.spaceId);if(room)for(const k of spaceCollections)room[k]=s[k];
  world.activeUserId=s.currentUser;world.people=s.people;world.preferences={...world.preferences,motionEnabled:s.motionEnabled,roomLit:s.roomLit===true};return persistWorld();
}
function currentSpace(){return world.spaces.find(s=>s.id===state.spaceId&&!s.archived&&s.memberIds.includes(state.currentUser))||null}
function members(){const ids=currentSpace()?.memberIds||[];return state.people.filter(p=>ids.includes(p.id))}
function currentConfirmations(rule){const ids=currentSpace()?.memberIds||[];return rule.confirmed.filter(id=>ids.includes(id))}
function isOwner(){return currentSpace()?.ownerId===state.currentUser}
function canDelete(entry){return !!currentSpace()&&(isOwner()||entry.createdBy===state.currentUser)}
function requireOwner(){if(!isOwner()){toast('这项操作仅房主可用');return false}return true}
function activity(message,room=currentSpace()){if(!room)return;room.activity.unshift({id:crypto.randomUUID(),user:state.currentUser,message,time:new Date().toISOString()});room.activity=room.activity.slice(0,100)}
function refreshSpace(){state=projectSpace();roomLit=state.roomLit;homeExpanded=false;page='home';persistWorld();init()}
function switchSpace(id){const target=joinedSpaces().find(s=>s.id===id);if(!target)return toast('你尚未加入这个空间');save();closeModal();world.activeSpaceId=id;refreshSpace()}
function switchPerson(id){if(!world.people.some(p=>p.id===id))return;const previousPage=page,previousSpace=state.spaceId;save();closeModal();world.activeUserId=id;state=projectSpace();roomLit=state.roomLit;homeExpanded=false;page=state.spaceId===previousSpace?previousPage:'home';persistWorld();init();toast(`已切换为 ${person(id).name}`)}
function updateSpaceChrome(){
  const alert=document.querySelector('#storage-alert');alert.hidden=!storageLocked;alert.textContent=storageLocked?'存储读取异常：已进入临时演示，不会覆盖原数据。请勿重置，联系恢复数据。':'';
  const room=currentSpace();document.querySelector('#space-label').textContent=room?.name||'尚未加入空间';document.querySelector('#space-members').textContent=room?`${room.memberIds.length} 位室友 · ${isOwner()?'我是房主':'我是成员'}`:'创建一个属于你的家';
  document.querySelector('#mobile-space-name').textContent=room?.name||'选择空间';
  document.querySelectorAll('.nav-btn').forEach(b=>b.disabled=!room&&b.dataset.page!=='home');
  document.body.classList.toggle('without-space',!room);
}
function spaceLobby(){return `${pageHead('A place to call home','给新的生活，留一个位置。','你目前没有加入的空间。创建一个，或使用房主给你的本地演示邀请。')}<section class="lobby-card"><div>${roomArt()}</div><h2>从一个空间开始</h2><p>空间拥有独立的账本、值日、物品与公约。<br>创建后，你就是这个空间的第一位房主。</p><button class="primary-btn" data-action="create-space">新建空间</button><button class="link-btn" data-action="join-space">我有邀请码</button></section>`}
function spaceSwitcher(){openModal('我的空间',`<p class="settings-intro">每个空间的成员、账单和日常记录独立保存。</p><div class="space-list">${joinedSpaces().map(r=>`<button type="button" class="space-choice ${r.id===state.spaceId?'selected':''}" data-action="switch-space" data-id="${r.id}"><span>${icon('home')}</span><span><b>${esc(r.name)}</b><small>${r.memberIds.length} 人 · ${r.ownerId===state.currentUser?'房主':'成员'}</small></span><em>${r.id===state.spaceId?'当前空间':'进入 →'}</em></button>`).join('')||'<p class="form-note">暂时没有加入的空间。</p>'}</div><div class="space-create-actions"><button type="button" class="primary-btn" data-action="create-space">＋ 新建空间</button><button type="button" class="secondary-btn" data-action="join-space">使用邀请码</button></div>`,()=>closeModal(),'完成');document.querySelector('.modal-actions').remove()}
function createSpaceForm(){openModal('新建合租空间',`<div class="field"><label>空间名称</label><input name="spaceName" maxlength="40" placeholder="例如：向阳里的小家" required></div><p class="form-note">你将成为房主。新空间从空白开始，不复制现有空间的数据。</p>`,fd=>{const name=String(fd.get('spaceName')).trim();if(!name||name.length>40)return error('请填写 1–40 字的空间名');save();const room=newSpaceData(name,state.currentUser);world.spaces.push(room);activity('创建了空间',room);closeModal();world.activeSpaceId=room.id;refreshSpace();toast('空间已创建，你是房主')},'创建空间')}
function renameSpace(){if(!requireOwner())return;const id=state.spaceId;openModal('修改空间名称',`<div class="field"><label>空间名称</label><input name="spaceName" maxlength="40" value="${esc(currentSpace().name)}"></div>`,fd=>{if(!requireOwner()||state.spaceId!==id)return;const name=String(fd.get('spaceName')).trim();if(!name||name.length>40)return error('请填写 1–40 字的空间名');const old=currentSpace().name;currentSpace().name=name;activity(`将空间「${old}」更名为「${name}」`);save();closeModal();render();toast('空间名称已更新')})}
const themeChoices=[['journal','暖居手账','奶油纸纹 · 植物剪影 · 午后微风'],['editorial','复古陶砖','奶油陶橙 · 棋盘瓷砖 · 印刷拼贴'],['night','月光玻璃','午夜蓝调 · 磨砂玻璃 · 流星与萤光']];
function applyTheme(){const theme=themeChoices.some(t=>t[0]===world.preferences?.theme)?world.preferences.theme:'journal';if(document.documentElement.dataset.theme===theme)return;document.documentElement.dataset.themeSwitching='true';document.documentElement.dataset.theme=theme;document.querySelector('meta[name=theme-color]').content=theme==='night'?'#151f29':theme==='editorial'?'#eeeae1':'#245c46';requestAnimationFrame(()=>requestAnimationFrame(()=>delete document.documentElement.dataset.themeSwitching))}
function openSpaceSettings(tab='space'){
  const room=currentSpace(),owner=isOwner();let body='';
  if(tab==='space')body=room?`<div class="space-overview"><span class="eyebrow">当前空间</span><h3>${esc(room.name)}</h3><p>${room.memberIds.length} 位室友 · 房主 ${esc(person(room.ownerId).name)}</p><span class="tag">${owner?'你是房主':'你是成员'}</span></div><div class="settings-commands">${owner?'<button type="button" class="secondary-btn" data-action="rename-space">修改空间名</button><button type="button" class="secondary-btn" data-action="share-space">分享 / 邀请</button>':''}<button type="button" class="secondary-btn" data-action="choose-space">切换 / 新建空间</button></div><div class="settings-row"><div><b>空间变更记录</b><small>成员、房主和空间名称的最近变更</small></div><button type="button" class="mini-btn" data-action="space-activity">查看</button></div><div class="settings-reset"><div><b>离开当前空间</b><small>先结清应付 / 应收款，交接未完成家务</small></div><button type="button" class="delete-btn" data-action="leave-space">离开</button></div>`:`<p class="form-note">你尚未加入空间。</p><button type="button" class="primary-btn" data-action="create-space">新建空间</button><button type="button" class="secondary-btn" data-action="join-space">使用邀请码</button>`;
  if(tab==='members')body=room?`<p class="settings-intro">${owner?'房主负责邀请、移除成员，并可删除空间内所有发布记录。':'普通成员可管理自己的发布记录；人员调整由房主负责。'}</p><div class="member-list">${members().map(p=>`<div class="member-row">${avatar(p.id)}<div><b>${esc(p.name)}${p.id===state.currentUser?'（我）':''}</b><small>${p.id===room.ownerId?'房主':'室友'}</small></div>${owner&&p.id!==state.currentUser?`<button type="button" class="delete-btn" data-action="remove-member" data-id="${p.id}">移除</button>`:''}</div>`).join('')}</div>${owner?'<div class="settings-commands"><button type="button" class="primary-btn" data-action="add-member">＋ 添加演示成员</button><button type="button" class="secondary-btn" data-action="transfer-owner">转让房主</button></div>':''}<p class="form-note">仅当前浏览器的演示成员，不会发送真实邀请消息。</p>`:'<p class="form-note">先加入一个空间，再查看室友。</p>';
  if(tab==='appearance')body=`<p class="settings-intro">不同风格，同一套生活功能。主题会应用于所有空间。</p><div class="theme-options">${themeChoices.map(([id,name,desc])=>`<button type="button" class="theme-choice ${world.preferences.theme===id?'selected':''}" data-action="set-theme" data-id="${id}" aria-pressed="${world.preferences.theme===id}"><span class="theme-preview preview-${id}"><i></i><i></i><i></i></span><b>${name}</b><small>${desc}</small>${world.preferences.theme===id?'<span class="theme-current">当前主题</span>':''}</button>`).join('')}</div><div class="settings-row"><div><b>小屋灯光</b><small>午后 / 暖灯，仅改变插画氛围</small></div><button type="button" class="mini-btn" data-action="toggle-light" aria-pressed="${roomLit}">${roomLit?'暖灯':'午后'}</button></div><div class="settings-row"><div><b>场景动效</b><small>拖把、泡泡、植物等；离屏自动暂停</small></div><button type="button" class="mini-btn" data-action="toggle-motion" aria-pressed="false">已开启</button></div>`;
  if(tab==='demo')body=`<div class="demo-banner">本地演示 · 无真实支付、账户验证和多人云端同步</div><div class="settings-row"><div><b>切换演示身份</b><small>可体验房主、室友及尚未加入空间的人</small></div><select id="current-user" aria-label="切换演示室友">${world.people.map(p=>`<option value="${p.id}" ${p.id===state.currentUser?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="settings-row"><div><b>我的昵称</b><small>修改后会同步显示在本地各空间的历史记录中</small></div><button type="button" class="mini-btn" data-action="rename-person">修改</button></div><div class="settings-row"><div><b>导出所有本地数据</b><small>下载 JSON 备份，包含空间、成员与业务记录</small></div><button type="button" class="mini-btn" data-action="export-spaces">导出</button></div><div class="settings-reset"><div><b>重置全部演示空间</b><small>会覆盖当前演示数据；操作前自动保留一份本地备份</small></div><button type="button" id="reset-btn" class="delete-btn" data-action="reset-demo">重置</button></div>`;
  const existing=document.querySelector('.settings-modal');
  if(existing){
    const focusKey=document.activeElement?.dataset.action==='set-theme'?document.activeElement.dataset.id:null;
    const panel=existing.querySelector('#settings-panel');panel.innerHTML=body;panel.scrollTop=0;panel.setAttribute('aria-labelledby','settings-tab-'+tab);
    existing.querySelectorAll('[data-action=settings-tab]').forEach(b=>{const selected=b.dataset.id===tab;b.classList.toggle('active',selected);b.setAttribute('aria-selected',String(selected));b.setAttribute('aria-pressed',String(selected));b.tabIndex=selected?0:-1});
    if(focusKey)existing.querySelector(`[data-action=set-theme][data-id="${focusKey}"]`)?.focus({preventScroll:true});
  }else{
    openModal('空间设置',`<div class="settings-tabs" role="tablist" aria-label="设置分类">${[['space','空间'],['members','成员'],['appearance','外观'],['demo','演示数据']].map(([id,label])=>`<button type="button" id="settings-tab-${id}" role="tab" aria-controls="settings-panel" tabindex="${tab===id?0:-1}" data-action="settings-tab" data-id="${id}" class="${tab===id?'active':''}" aria-selected="${tab===id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</div><section id="settings-panel" role="tabpanel" aria-labelledby="settings-tab-${tab}">${body}</section>`,()=>closeModal(),'完成');
    document.querySelector('.modal').classList.add('settings-modal');document.querySelector('.modal-actions [data-action=close]').remove();
  }
  syncAmbient();
}
document.addEventListener('keydown',e=>{if(!e.target.matches('.settings-tabs [role=tab]')||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...e.target.parentElement.children],i=tabs.indexOf(e.target),next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;openSpaceSettings(tabs[next].dataset.id);tabs[next].focus()});
function addMemberForm(){if(!requireOwner())return;const room=currentSpace(),available=world.people.filter(p=>!room.memberIds.includes(p.id));openModal('添加演示成员',`<p class="form-note">加入当前空间后，可切换成该身份体验。不会邀请真实用户。</p><div class="field"><label>选择已有演示身份</label><select name="existing"><option value="">新建一个身份</option>${available.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field" style="margin-top:16px"><label>新成员昵称（新建身份时填写）</label><input name="name" maxlength="16" placeholder="例如：小夏"></div>`,fd=>{if(!requireOwner()||currentSpace()?.id!==room.id)return;let id=fd.get('existing');if(id){if(!available.some(p=>p.id===id)||room.memberIds.includes(id))return error('这位成员已加入，或身份不存在')}else{const name=String(fd.get('name')).trim();if(!name||name.length>16)return error('请填写 1–16 字昵称');if(members().some(p=>p.name===name))return error('当前空间已有同名成员，请使用不同昵称');id=uid('u');world.people.push({id,name,color:['#3f7a5e','#c9822c','#6683a3','#a66c70'][world.people.length%4]})}room.memberIds.push(id);activity(`添加成员 ${person(id).name}`);save();closeModal();render();toast('成员已加入；可在演示数据中切换身份')},'添加成员')}
function transferOwner(){if(!requireOwner())return;const room=currentSpace(),others=members().filter(p=>p.id!==state.currentUser);if(!others.length)return toast('先添加另一位成员，才能转让房主');openModal('转让房主',`<p class="form-note">转让后你成为普通成员，对方获得改名、邀请、移除及删除所有记录的权限。</p><div class="field"><label>新房主</label><select name="owner">${others.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div>`,fd=>{if(!requireOwner()||currentSpace()?.id!==room.id)return;const next=fd.get('owner');if(next===state.currentUser||!room.memberIds.includes(next))return error('请选择仍在空间中的其他成员');activity(`将房主转让给 ${person(next).name}`);room.ownerId=next;save();closeModal();render();toast('房主已转让，你现在是普通成员')},'确认转让')}
function departureDebt(id){let owed=0,receivable=0;for(const e of state.expenses){if(e.participants.includes(id)&&!e.settled.includes(id))owed+=e.shares[id]||0;if(e.payer===id)for(const p of e.participants)if(p!==id&&!e.settled.includes(p))receivable+=e.shares[p]||0}return {owed,receivable}}
function departMember(id){
  const room=currentSpace();if(!room||!room.memberIds.includes(id))return;const self=id===state.currentUser;if(!self&&!requireOwner())return;
  if(id===room.ownerId&&room.memberIds.length>1)return openModal('请先转让房主','<p class="form-note">空间中还有其他室友。先在「成员」中转让房主，再离开，避免空间无人管理。</p>',()=>closeModal(),'知道了');
  const debt=departureDebt(id),pending=state.chores.filter(x=>x.person===id&&x.status!=='done'),others=members().filter(p=>p.id!==id),blocked=debt.owed>0||debt.receivable>0;
  openModal(self?'离开这个空间？':`移除 ${person(id).name}？`,`<p class="form-note">${self?'你':esc(person(id).name)}将退出「${esc(room.name)}」。历史账单、发布者与物品流水仍会保留。</p>${blocked?`<div class="departure-warning">暂不能退出：待结算 ${money(debt.owed)}，待收齐 ${money(debt.receivable)}。请先在共同账本中完成相关结算。</div>`:''}${pending.length&&others.length?`<div class="field"><label>${pending.length} 项未完成家务交接给</label><select name="handover">${others.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div>`:''}<p class="form-note">采购认领将释放，已完成家务保留原负责人。${others.length?'':'你是最后一位成员，退出后该空间会归档。'}</p>`,fd=>{
    if(currentSpace()?.id!==room.id||(!self&&!isOwner()))return error('空间或权限已变化，请重新操作');const d=departureDebt(id);if(d.owed>0||d.receivable>0)return error('请先结清应付和应收款项');if(id===room.ownerId&&room.memberIds.length>1)return error('请先转让房主');
    const target=fd.get('handover');if(pending.length&&others.length&&!others.some(p=>p.id===target))return error('请选择任务接手人');for(const x of pending)if(others.length)x.person=target;for(const x of state.items)if(x.claimedBy===id)x.claimedBy=null;
    activity(`${self?'离开空间：':'移除成员：'}${person(id).name}`);room.memberIds=room.memberIds.filter(p=>p!==id);room.departedMembers=room.departedMembers||[];room.departedMembers.push({id,time:new Date().toISOString()});if(!room.memberIds.length)room.archived=true;save();closeModal();if(self)refreshSpace();else render();toast(self?'已离开空间，历史记录保留':'成员已移除，交接已完成');
  },self?'确认离开':'确认移除');
}
function renamePerson(){openModal('修改我的昵称',`<div class="field"><label>昵称</label><input name="name" maxlength="16" value="${esc(person(state.currentUser).name)}"></div>`,fd=>{const name=String(fd.get('name')).trim();if(!name||name.length>16)return error('请填写 1–16 字昵称');if(members().some(p=>p.id!==state.currentUser&&p.name===name))return error('空间中已有同名成员');person(state.currentUser).name=name;save();closeModal();render();toast('昵称已更新')})}
function invitationLink(room){const payload={v:1,id:room.id,name:room.name,owner:person(room.ownerId).name,token:room.inviteToken};return `${location.origin}${location.pathname}#invite=${encodeURIComponent(JSON.stringify(payload))}`}
function shareSpace(){if(!requireOwner())return;const room=currentSpace();if(!room.inviteToken)room.inviteToken=crypto.randomUUID();save();openModal('分享空间 · 演示邀请',`<div class="demo-banner">同一浏览器可演示加入；其他浏览器只能预览邀请，不会同步空间数据。</div><p class="form-note">仅包含空间名称、房主昵称和演示邀请码，不包含账单或流水。</p><div class="field"><label>邀请链接</label><textarea id="invite-link" readonly rows="4">${esc(invitationLink(room))}</textarea></div><div class="settings-commands"><button type="button" class="primary-btn" data-action="copy-invite">复制邀请链接</button><button type="button" class="secondary-btn" data-action="rotate-invite">使旧邀请失效</button></div>`,()=>closeModal(),'完成');document.querySelector('.modal-actions [data-action=close]').remove()}
function joinSpaceForm(invite=null){
  openModal(invite?'空间邀请':'加入演示空间',`${invite?`<div class="space-overview"><h3>${esc(invite.name)}</h3><p>${esc(invite.owner)} 邀请你加入</p></div>`:''}<div class="demo-banner">仅能加入本浏览器已有的演示空间。跨设备同步需后端，当前未接入。</div><div class="field" style="margin-top:18px"><label>邀请链接</label><textarea name="invite" rows="3" placeholder="粘贴房主分享的完整链接">${invite?esc(`${location.origin}${location.pathname}#invite=${encodeURIComponent(JSON.stringify(invite))}`):''}</textarea></div>`,fd=>{
    let input;try{input=readInvite(String(fd.get('invite')))}catch{return error('邀请格式无效，请复制完整链接')}
    const room=world.spaces.find(s=>s.id===input.id&&!s.archived);if(!room)return error('此空间不在当前浏览器中。这里只能预览邀请，不能跨设备加入或同步。');if(room.inviteToken!==input.token)return error('邀请已失效，请向房主索取新链接');
    save();if(!room.memberIds.includes(state.currentUser)){room.memberIds.push(state.currentUser);activity(`${person(state.currentUser).name} 通过本地邀请加入`,room)}closeModal();world.activeSpaceId=room.id;refreshSpace();history.replaceState(null,'',location.pathname+location.search);toast('已加入本地演示空间');
  },'在本浏览器加入');
}
function readInvite(input){const url=new URL(input,location.origin);const text=new URLSearchParams(url.hash.slice(1)).get('invite');if(!text||text.length>3000)throw Error();const data=JSON.parse(text);if(data.v!==1||typeof data.id!=='string'||typeof data.token!=='string'||typeof data.name!=='string'||typeof data.owner!=='string'||data.name.length>100)throw Error();return data}
function checkInvitation(){if(!location.hash.startsWith('#invite='))return;try{joinSpaceForm(readInvite(location.href))}catch{toast('邀请链接格式无效，已忽略')}}
function exportSpaces(){save();const blob=new Blob([JSON.stringify(world,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`wuli-spaces-${dateValue()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);toast('已生成本地数据备份')}
function resetAllSpaces(){if(!confirm('确定重置全部本地空间？所有现有修改会被替换为示例；重置前会保留本地备份。'))return;try{localStorage.setItem('wuli_housemate_backup_before_reset',JSON.stringify(world))}catch{return toast('无法保存重置备份，已取消重置')}const seed=migrateData(structuredClone(demo)),room=newSpaceData('春和里 · 6 栋',seed.people[0].id);room.memberIds=seed.people.map(p=>p.id);for(const k of spaceCollections)room[k]=seed[k];world={version:3,people:seed.people,activeUserId:seed.currentUser,activeSpaceId:room.id,spaces:[room],preferences:{theme:world.preferences.theme,motionEnabled:true,roomLit:false}};closeModal();refreshSpace();toast('演示空间已重置，原数据已备份')}
document.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b)return;const a=b.dataset.action,id=b.dataset.id;
  if(a==='choose-space')spaceSwitcher();if(a==='switch-space')switchSpace(id);if(a==='create-space')createSpaceForm();if(a==='rename-space')renameSpace();if(a==='settings-tab')openSpaceSettings(id);
  if(a==='add-member')addMemberForm();if(a==='transfer-owner')transferOwner();if(a==='remove-member')departMember(id);if(a==='leave-space')departMember(state.currentUser);if(a==='rename-person')renamePerson();if(a==='join-space')joinSpaceForm();if(a==='share-space')shareSpace();if(a==='export-spaces')exportSpaces();
  if(a==='set-theme'&&themeChoices.some(t=>t[0]===id)){world.preferences.theme=id;save();applyTheme();openSpaceSettings('appearance')}
  if(a==='rotate-invite'&&requireOwner()){if(!confirm('更新邀请码后，旧链接将无法加入。是否继续？'))return;currentSpace().inviteToken=crypto.randomUUID();activity('更新了演示邀请链接');save();shareSpace()}
  if(a==='copy-invite'){const input=document.querySelector('#invite-link');try{await navigator.clipboard.writeText(input.value);toast('已复制演示邀请链接')}catch{input.focus();input.select();toast('请按 Ctrl+C，或长按选择复制链接')}}
  if(a==='space-activity'){openModal('空间变更记录',`<div class="list">${currentSpace().activity.map(x=>`<div class="list-row"><div class="row-main"><b>${esc(x.message)}</b><small>${esc(person(x.user).name)} · ${deadlineText(x.time)}</small></div></div>`).join('')||'<p class="form-note">暂时没有空间变更。</p>'}</div>`,()=>closeModal(),'完成')}
});
