function homeView(){
  const me=person(state.currentUser),pending=pendingFor(me.id);
  const tasks=state.chores.filter(x=>x.person===me.id&&x.status!=='done');
  const low=state.items.filter(x=>x.qty<=x.threshold),unconfirmed=state.rules.filter(x=>!x.confirmed.includes(me.id));
  const date=new Date(),hour=date.getHours(),greeting=hour<11?'早上好':hour<14?'中午好':hour<18?'下午好':'晚上好';
  const dateText=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(date);
  const allConfirmed=state.rules.filter(x=>x.confirmed.length===state.people.length).length;
  return `<div class="home-welcome"><div><span class="welcome-date">${dateText} · 屋里的日常</span><h1>${greeting}，${esc(me.name)}。</h1><p>欢迎回家，今天的小事也一起照顾好。</p></div><span class="room-label">${icon('home')} 春和里 · 6 栋</span></div>
  <section class="hero ${roomLit?'is-evening':''}" aria-label="屋里，共同生活"><div class="hero-copy"><span class="hero-kicker">${icon('leaf')} 一起住，也一起好好生活</span><h2>把小事理清，<br>把日子<em>过成喜欢。</em></h2><p>算清一笔账，分担一点家务。<br>让每一份付出被看见，让合租多一点家的温度。</p><div class="hero-actions"><button class="primary-btn" data-action="add-expense">${icon('plus')} 记一笔共同开支</button><button class="link-btn" data-page="chores">看看本周值日 ${icon('arrow')}</button></div></div><div class="hero-art">${roomArt()}<div class="house-stamp"><b>好好生活</b><small>OUR LITTLE HOME</small></div><button class="scene-toggle" data-action="toggle-light" aria-pressed="${roomLit}" aria-label="切换小屋灯光">${icon('sun')}<span>${roomLit?'回到午后':'点亮小屋'}</span></button><span class="art-caption">a little room, a lot of life.</span></div></section>
  <div class="stats" aria-label="我的生活摘要">
    ${statCard('expenses','expenses','我的待结算',money(pending),'线下结清，账目明明白白')}
    ${statCard('chores','chores','我的值日',`${tasks.length}<small>项</small>`,tasks.length?'顺手照顾一下我们的家':'都完成了，辛苦啦')}
    ${statCard('items','items','物品待补货',`${low.length}<small>件</small>`,low.length?'出门时记得顺路带上':'物品柜的储备很充足')}
    ${statCard('rules','rules','公约待确认',`${unconfirmed.length}<small>条</small>`,unconfirmed.length?'让我们的默契再多一点':'我们的约定，你都确认了')}
  </div>
  <div class="section-heading"><h2>屋里进行时 <span>Little things, together.</span></h2><span>每一份付出，都算数</span></div>
  <div class="dashboard-grid"><section class="card"><div class="card-head"><div><h2>我的值日清单</h2><small>一点小劳动，一屋好心情</small></div><button class="link-btn" data-page="chores">全部 ${icon('arrow')}</button></div><div class="list">${tasks.slice(0,3).map(x=>`<div class="list-row"><button class="check-circle" data-action="toggle-chore" data-id="${x.id}" aria-label="完成${esc(x.area)}">${icon('check')}</button><div class="row-main"><b>${esc(x.area)}</b><small>${esc(x.due)} · ${esc(me.name)}负责</small></div><span class="tag ${x.status==='overdue'?'red':''}">${x.status==='overdue'?'已逾期':'待完成'}</span></div>`).join('')||'<div class="empty"><b>今日份家务，完成。</b>泡杯茶，享受一下这个干净的家。</div>'}</div><div class="household-strip"><span>${icon('heart')} 做完记得打个勾，辛苦啦。</span></div></section>
  <section class="card"><div class="card-head"><div><h2>顺路带点回来</h2><small>公共物品，一起补给</small></div><button class="link-btn" data-page="items">物品柜 ${icon('arrow')}</button></div><div class="list">${low.slice(0,3).map(x=>`<div class="list-row"><span class="row-symbol">${icon('items')}</span><div class="row-main"><b>${esc(x.name)}</b><small>剩 ${x.qty}${esc(x.unit)} · 该补货啦</small></div>${x.claimedBy?`<span class="tag">${esc(person(x.claimedBy).name)}来买</span>`:`<button class="mini-btn" data-action="claim" data-id="${x.id}">我来买</button>`}</div>`).join('')||'<div class="empty"><b>物品储备充足</b>谢谢每一位顺手补货的室友。</div>'}</div></section>
  <section class="card note-card"><span class="note-kicker">${icon('sparkle')} 屋里的小默契</span><blockquote>好的室友，<br>从把话说清开始。</blockquote><p>${allConfirmed} 条公约已达成全员共识。<br>把“我以为”变成“我们约定”。</p><button class="link-btn" data-page="rules">看看我们的公约 ${icon('arrow')}</button></section></div>
  <div class="household-strip"><div class="household-people"><div class="avatar-group">${state.people.map(p=>avatar(p.id)).join('')}</div><span>${state.people.length} 位室友，共同照顾这个家</span></div><span>${icon('leaf')} 日子慢慢过，小事一起做。</span></div>`;
}
function statCard(dest,symbol,title,value,description){return `<button class="stat" data-page="${dest}"><span class="stat-top">${icon(symbol)}${title}</span><strong>${value}</strong><small>${description}</small>${icon('arrow','stat-arrow')}</button>`}
function expenseView(){
  const list=state.expenses.filter(e=>expenseMode==='all'||(expenseMode==='mine'&&e.participants.includes(state.currentUser))||(expenseMode==='unsettled'&&e.participants.includes(state.currentUser)&&!e.settled.includes(state.currentUser)));
  return `${pageHead('01 / Shared expenses','一起花，清楚算。','每一笔共同开支，都有明明白白的去向。',`<button class="primary-btn" data-action="add-expense">${icon('plus')} 记一笔</button>`)}
  <div class="summary-banner"><div><p>我还需要线下结算</p><strong>${money(pendingFor(state.currentUser))}</strong></div><span>大方分享生活，<br>也认真对待每一笔小钱。</span></div>
  <div class="toolbar"><div class="segmented" aria-label="账单筛选">${[['all','全部账单'],['mine','与我相关'],['unsettled','待结算']].map(([id,label])=>`<button data-filter="${id}" class="${expenseMode===id?'active':''}" aria-pressed="${expenseMode===id}">${label}</button>`).join('')}</div><span class="tag">${list.length} 笔共同开支</span></div>
  <div class="expense-list">${list.map(e=>{const involved=e.participants.includes(state.currentUser),settled=e.settled.includes(state.currentUser);return `<article class="receipt"><div class="receipt-left"><span class="receipt-icon">${icon('expenses')}</span><div><h3>${esc(e.title)}</h3><p>${esc(e.date)} · ${esc(person(e.payer).name)}垫付 · ${e.participants.length}人分摊</p></div></div><div class="receipt-right"><strong>${money(e.amount)}</strong><span class="tag ${involved&&!settled?'warn':''}">${involved?(settled?'我已结清':'我待结算'):'未参与分摊'}</span></div><div class="receipt-footer"><span>${involved?`我承担 <b>${money(e.shares[state.currentUser])}</b> · `:''}${e.participants.map(id=>esc(person(id).name)).join(' / ')}</span><div class="toolbar" style="margin:0;gap:7px"><button class="link-btn" data-action="expense-detail" data-id="${e.id}">分摊明细</button>${involved&&!settled?`<button class="mini-btn" data-action="settle" data-id="${e.id}">标记结清</button>`:''}</div></div></article>`}).join('')||'<div class="card empty"><b>这里清清爽爽。</b>还没有符合条件的账单，记一笔新的共同开支吧。</div>'}</div>`;
}
function choreView(){const done=state.chores.filter(x=>x.status==='done').length;return `${pageHead('02 / A little teamwork','家务分着做，日子轻一点。','不让“总是我来”变成心结，一起照顾公共空间。',`<button class="primary-btn" data-action="add-chore">${icon('plus')} 添加任务</button>`)}<div class="toolbar"><span class="tag">本周排班 · ${done} / ${state.chores.length} 项已完成</span><span class="date-label">${icon('heart')} 每一次劳动，都值得被看见</span></div><div class="data-grid">${state.chores.map((x,i)=>`<article class="item-card chore-card ${x.status==='done'?'completed':''}"><div class="chore-visual"><span class="chore-index">HOUSEWORK / ${String(i+1).padStart(2,'0')}</span>${icon(/厨房/.test(x.area)?'tea':/客厅|阳台/.test(x.area)?'leaf':'chores')}</div><div class="item-card-top"><div><h3>${esc(x.area)}</h3><p>${icon('clock')} ${esc(x.due)}</p></div><span class="tag ${x.status==='overdue'?'red':x.status==='pending'?'warn':''}">${x.status==='done'?'✓ 已完成':x.status==='overdue'?'已逾期':'待完成'}</span></div><div class="task-person">${avatar(x.person)}<span>${esc(person(x.person).name)}</span><small>本次负责人</small></div><div class="item-card-actions"><button class="${x.status==='done'?'mini-btn':'primary-btn'}" data-action="toggle-chore" data-id="${x.id}">${x.status==='done'?'撤销完成':`${icon('check')} 标记完成`}</button><button class="mini-btn" data-action="reassign" data-id="${x.id}">调整负责人</button></div></article>`).join('')}</div>`}
function itemView(){return `${pageHead('03 / Our shared shelf','小小物品柜，满满生活感。','消耗有记录，补货有人管，让“谁来买”不再尴尬。',`<button class="primary-btn" data-action="add-item">${icon('plus')} 登记物品</button>`)}<div class="toolbar"><span class="tag">共 ${state.items.length} 件公共物品</span><span class="date-label">${icon('leaf')} 顺手补一件，也是一份照顾</span></div><div class="data-grid">${state.items.map(x=>{const low=x.qty<=x.threshold,pct=Math.min(100,Math.max(0,x.qty/Math.max(1,x.threshold*3)*100));return `<article class="item-card supply-card ${low?'low':''}"><div class="supply-stage">${supplyArt(x.name)}<span class="tag ${low?'warn':''}">${low?'该补货啦':'储备充足'}</span></div><div class="item-card-top"><div><h3>${esc(x.name)}</h3><p>提醒阈值 ${x.threshold}${esc(x.unit)}</p></div><span class="supply-quantity">${x.qty}<small>${esc(x.unit)}</small></span></div><div class="progress ${low?'warn':''}"><i style="width:${pct}%"></i></div><div class="item-card-actions"><button class="mini-btn" data-action="item-change" data-kind="consume" data-id="${x.id}">− 消耗</button><button class="mini-btn" data-action="item-change" data-kind="restock" data-id="${x.id}">＋ 补货</button>${low&&!x.claimedBy?`<button class="mini-btn" data-action="claim" data-id="${x.id}">我来买</button>`:''}<button class="link-btn" data-action="logs" data-id="${x.id}">记录 ${x.logs.length}</button></div>${x.claimedBy?`<p class="claim-note">${icon('check')} ${esc(person(x.claimedBy).name)}已认领采购</p>`:''}</article>`}).join('')}</div>`}
function ruleView(){return `${pageHead('04 / Better together','一起住，也有共同的约定。','把边界说清，把体谅留下。我们的家，我们共同决定。',`<button class="primary-btn" data-action="add-rule">${icon('plus')} 新建公约</button>`)}<div class="rule-grid">${state.rules.map((x,i)=>{const ok=x.confirmed.includes(state.currentUser);return `<article class="card rule-card"><div class="item-card-top"><span class="rule-number">Agreement ${String(i+1).padStart(2,'0')}</span><span class="tag">${esc(x.category)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p><div class="rule-signatures"><div class="avatar-group">${x.confirmed.map(id=>avatar(id)).join('')}</div><span>${x.confirmed.length} / ${state.people.length} 位室友已确认</span></div><div class="progress"><i style="width:${x.confirmed.length/state.people.length*100}%"></i></div><div class="item-card-actions"><button class="${ok?'secondary-btn':'primary-btn'}" data-action="confirm-rule" data-id="${x.id}" ${ok?'disabled':''}>${ok?'✓ 我已确认':'我同意这条约定'}</button><button class="mini-btn" data-action="edit-rule" data-id="${x.id}">编辑公约</button></div></article>`}).join('')}</div>`}
