function homeView(){
  const me=person(state.currentUser),tasks=myTodayChores(),low=lowItems(),bills=myUrgentBills();
  const unconfirmed=state.rules.filter(x=>!x.confirmed.includes(me.id)),date=new Date(),hour=date.getHours(),greeting=hour<11?'早上好':hour<14?'中午好':hour<18?'下午好':'晚上好';
  const dateText=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(date);
  return `<div class="home-welcome"><div><span class="welcome-date">${dateText} · 屋里的日常</span><h1>${greeting}，${esc(me.name)}。</h1><p>欢迎回家，先照顾眼前的几件小事。</p></div><span class="room-label">${icon('home')} 春和里 · 6 栋</span></div>
  <section class="hero ${roomLit?'is-evening':''}" aria-label="屋里，共同生活"><div class="hero-copy"><span class="hero-kicker">${icon('leaf')} 一起住，也一起好好生活</span><h2>把小事理清，<br>把日子<em>过成喜欢。</em></h2><p>算清一笔账，分担一点家务。<br>让每一份付出被看见，让合租多一点家的温度。</p><div class="hero-actions"><button class="primary-btn" data-action="add-expense">${icon('plus')} 记一笔共同开支</button><button class="link-btn" data-page="chores">看看值日安排 ${icon('arrow')}</button></div><button class="motion-toggle" data-action="toggle-motion" aria-pressed="true">微风轻动 · 开</button></div><div class="hero-art">${roomArt()}${ambientArt()}<div class="house-stamp"><b>好好生活</b><small>OUR LITTLE HOME</small></div><button class="scene-toggle" data-action="toggle-light" aria-pressed="${roomLit}" aria-label="切换小屋灯光">${icon('sun')}<span>${roomLit?'回到午后':'点亮小屋'}</span></button><span class="art-caption">a little room, a lot of life.</span></div></section>
  <div class="stats" aria-label="我的生活摘要">
    ${statCard('expenses','expenses','即将到期的账',money(bills.reduce((s,x)=>s+x.shares[me.id],0)),`${bills.length} 笔 · 含逾期及未来 72 小时`)}
    ${statCard('chores','chores','今天要照顾的家',`${tasks.length}<small>项</small>`,'我的今日任务与逾期未完成')}
    ${statCard('items','items','物品待补货',`${low.length}<small>件</small>`,'先补最缺的，不错过最后一卷')}
    ${statCard('rules','rules','公约待确认',`${unconfirmed.length}<small>条</small>`,unconfirmed.length?'让我们的默契再多一点':'我们的约定，你都确认了')}
  </div>
  <div class="section-heading"><h2>先照顾这些小事 <span>A little care, right now.</span></h2><span>按紧急程度排序 · 每类最多 3 条</span></div>
  <div class="dashboard-grid">
    <section class="card" data-summary="chores"><div class="card-head"><div><h2>今天的值日</h2><small>含逾期未完成 · 只看我负责的</small></div><button class="link-btn" data-page="chores">全部 ${icon('arrow')}</button></div><div class="list">${tasks.slice(0,3).map(x=>`<div class="list-row"><button class="check-circle" data-action="toggle-chore" data-id="${x.id}" aria-label="完成${esc(x.area)}">${icon('check')}</button><div class="row-main"><b>${esc(x.area)}</b><small>${deadlineText(x.dueAt)}</small></div><span class="tag ${choreStatus(x)==='overdue'?'red':''}">${choreStatus(x)==='overdue'?'已逾期':'今天'}</span></div>`).join('')||emptyState('今天暂时没有待办','未来任务可在值日排班查看。','chores','看看排班',true)}</div>${tasks.length>3?`<p class="summary-more">另有 ${tasks.length-3} 项，前往值日查看</p>`:''}</section>
    <section class="card" data-summary="items"><div class="card-head"><div><h2>快用完的物品</h2><small>按剩余比例排序 · 一起补给</small></div><button class="link-btn" data-page="items">物品柜 ${icon('arrow')}</button></div><div class="list">${low.slice(0,3).map(x=>`<div class="list-row"><span class="row-symbol">${picture(x.iconId)}</span><div class="row-main"><b>${esc(x.name)}</b><small>${x.qty===0?'已经用完':`剩 ${x.qty}${esc(x.unit)}`} · ${x.claimedBy?esc(person(x.claimedBy).name)+'来买':'等待补货'}</small></div>${!x.claimedBy?`<button class="mini-btn" data-action="claim" data-id="${x.id}">我来买</button>`:'<span class="tag">已认领</span>'}</div>`).join('')||emptyState('物品储备充足','谢谢每位顺手补货的室友。','items','打开物品柜',true)}</div>${low.length>3?`<p class="summary-more">另有 ${low.length-3} 件需要补货</p>`:''}</section>
    <section class="card urgent-bills" data-summary="expenses"><div class="card-head"><div><h2>别忘了这几笔</h2><small>我的待结算 · 逾期及未来 72 小时</small></div><button class="link-btn" data-page="expenses">账本 ${icon('arrow')}</button></div><div class="list">${bills.slice(0,3).map(x=>`<div class="list-row"><span class="row-symbol">${picture(x.iconId)}</span><div class="row-main"><b>${esc(x.title)}</b><small>${Date.parse(x.dueAt)<Date.now()?'已逾期 · ':''}${deadlineText(x.dueAt)}</small><strong class="urgent-amount">${money(x.shares[me.id])}</strong></div><button class="mini-btn" data-action="settle" data-id="${x.id}">结算</button></div>`).join('')||emptyState('近期没有待结算账单','其他账单可到共同账本查看。','expenses','查看全部账单',true)}</div>${bills.length>3?`<p class="summary-more">另有 ${bills.length-3} 笔即将到期</p>`:''}<p class="demo-footnote">演示支付，不涉及真实资金。</p></section>
  </div><div class="household-strip"><div class="household-people"><div class="avatar-group">${state.people.map(p=>avatar(p.id)).join('')}</div><span>${state.people.length} 位室友，共同照顾这个家</span></div><span>${icon('leaf')} 日子慢慢过，小事一起做。</span></div>`;
}
function statCard(dest,symbol,title,value,description){return `<button class="stat" data-page="${dest}"><span class="stat-top">${icon(symbol)}${title}</span><strong>${value}</strong><small>${description}</small>${icon('arrow','stat-arrow')}</button>`}
function emptyState(title,text,dest,label,navigate=false){return `<div class="empty"><b>${title}</b><p>${text}</p><button class="link-btn" ${navigate?'data-page':'data-action'}="${dest}">${label} ${icon('arrow')}</button></div>`}
function expenseView(){
  const list=state.expenses.filter(e=>expenseMode==='all'||(expenseMode==='mine'&&e.participants.includes(state.currentUser))||(expenseMode==='unsettled'&&e.participants.includes(state.currentUser)&&!e.settled.includes(state.currentUser)));
  return `${pageHead('01 / Shared expenses','一起花，清楚算。','每一笔共同开支，都有明明白白的去向。',`<button class="primary-btn" data-action="add-expense">${icon('plus')} 记一笔</button>`)}
  <div class="summary-banner"><div><p>我的待结算 · 演示账本</p><strong>${money(pendingFor(state.currentUser))}</strong></div><span>选择支付方式 → 模拟支付 → 更新结清<br>仅演示流程，不扣款、不连接支付平台。</span></div>
  <div class="toolbar"><div class="segmented" aria-label="账单筛选">${[['all','全部账单'],['mine','与我相关'],['unsettled','待结算']].map(([id,label])=>`<button data-filter="${id}" class="${expenseMode===id?'active':''}" aria-pressed="${expenseMode===id}">${label}</button>`).join('')}</div><span class="tag">${list.length} 笔共同开支</span></div>
  <div class="expense-list">${list.map(e=>{const involved=e.participants.includes(state.currentUser),settled=e.settled.includes(state.currentUser),paid=e.payments?.some(p=>p.user===state.currentUser);return `<article class="receipt" data-entry-id="${e.id}"><div class="receipt-left"><span class="receipt-icon">${picture(e.iconId)}</span><div><h3>${esc(e.title)}</h3><p>${esc(e.date)} · ${esc(person(e.payer).name)}垫付 · ${e.participants.length}人分摊</p><p class="${involved&&!settled&&Date.parse(e.dueAt)<Date.now()?'deadline-overdue':''}">${icon('clock')} ${e.dueAt?deadlineText(e.dueAt)+' 截止':'旧账单未设置截止日期'}${involved&&!settled&&Date.parse(e.dueAt)<Date.now()?' · 已逾期':''}</p></div></div><div class="receipt-right"><strong>${money(e.amount)}</strong><span class="tag ${involved&&!settled?'warn':''}">${involved?(settled?(paid?'演示已结清':e.payer===state.currentUser?'本人已垫付':'已结清 · 原有记录'):'我待结算'):'未参与分摊'}</span></div><div class="receipt-footer"><span>${involved?`我承担 <b>${money(e.shares[state.currentUser])}</b> · `:''}${e.participants.map(id=>esc(person(id).name)).join(' / ')}</span><div class="toolbar" style="margin:0;gap:7px"><button class="link-btn" data-action="expense-detail" data-id="${e.id}">分摊明细</button>${involved&&!settled?`<button class="mini-btn" data-action="settle" data-id="${e.id}">结算</button>`:''}</div></div>${authorship(e,'expenses')}</article>`}).join('')||emptyState('这里清清爽爽。','还没有符合条件的账单。','add-expense','记一笔共同开支')}</div>`;
}
function choreView(){
  const list=[...state.chores].sort(byDeadline),done=list.filter(x=>x.status==='done').length;
  return `${pageHead('02 / A little teamwork','家务分着做，日子轻一点。','不让“总是我来”变成心结，一起照顾公共空间。',`<button class="primary-btn" data-action="add-chore">${icon('plus')} 添加任务</button>`)}
  <div class="toolbar"><span class="tag">全部排班 · ${done} / ${list.length} 项已完成</span><span class="date-label">${icon('clock')} 按完成时间从近到远 · 逾期在前</span></div><div class="data-grid">${list.map((x,i)=>{const status=choreStatus(x);return `<article class="item-card chore-card ${status==='done'?'completed':''}" data-entry-id="${x.id}"><div class="chore-visual"><span class="chore-index">HOUSEWORK / ${String(i+1).padStart(2,'0')}</span>${picture(x.iconId)}</div><div class="item-card-top"><div><h3>${esc(x.area)}</h3><p>${icon('clock')} ${x.dueAt?deadlineText(x.dueAt):esc(x.due||'未设置')+' · 请补全日期'}</p></div><span class="tag ${status==='overdue'?'red':status==='pending'?'warn':''}">${status==='done'?'✓ 已完成':status==='overdue'?'已逾期':'待完成'}</span></div><div class="task-person">${avatar(x.person)}<span>${esc(person(x.person).name)}</span><small>本次负责人</small></div><div class="item-card-actions"><button class="${status==='done'?'mini-btn':'primary-btn'}" data-action="toggle-chore" data-id="${x.id}">${status==='done'?'撤销完成':`${icon('check')} 标记完成`}</button><button class="mini-btn" data-action="reassign" data-id="${x.id}">换人</button><button class="link-btn" data-action="reschedule" data-id="${x.id}">改时间</button></div>${authorship(x,'chores')}</article>`}).join('')||emptyState('还没有值日安排','从一件小家务开始，一起分担。','add-chore','添加任务')}</div>`;
}
function itemView(){return `${pageHead('03 / Our shared shelf','小小物品柜，满满生活感。','消耗有记录，补货有人管，让“谁来买”不再尴尬。',`<button class="primary-btn" data-action="add-item">${icon('plus')} 登记物品</button>`)}<div class="toolbar"><span class="tag">共 ${state.items.length} 件公共物品</span><span class="date-label">${icon('leaf')} 顺手补一件，也是一份照顾</span></div><div class="data-grid">${state.items.map(x=>{const low=x.qty<=x.threshold,pct=Math.min(100,Math.max(0,x.qty/Math.max(1,x.threshold*3)*100));return `<article class="item-card supply-card ${low?'low':''}" data-entry-id="${x.id}"><div class="supply-stage picture-stage theme-${pictureCatalog.findIndex(p=>p[0]===x.iconId)%4}"><span class="picture-orbit"></span>${picture(x.iconId,'supply-picture')}<span class="tag ${low?'warn':''}">${low?(x.qty===0?'已经用完':'该补货啦'):'储备充足'}</span></div><div class="item-card-top"><div><h3>${esc(x.name)}</h3><p>提醒阈值 ${x.threshold}${esc(x.unit)}</p></div><span class="supply-quantity">${x.qty}<small>${esc(x.unit)}</small></span></div><div class="progress ${low?'warn':''}"><i style="width:${pct}%"></i></div><div class="item-card-actions"><button class="mini-btn" data-action="item-change" data-kind="consume" data-id="${x.id}">− 消耗</button><button class="mini-btn" data-action="item-change" data-kind="restock" data-id="${x.id}">＋ 补货</button>${low&&!x.claimedBy?`<button class="mini-btn" data-action="claim" data-id="${x.id}">我来买</button>`:''}<button class="link-btn" data-action="logs" data-id="${x.id}">记录 ${x.logs.length}</button></div>${x.claimedBy?`<p class="claim-note">${icon('check')} ${esc(person(x.claimedBy).name)}已认领采购</p>`:''}${authorship(x,'items')}</article>`}).join('')||emptyState('物品柜等你整理','把大家一起用的东西记下来。','add-item','登记第一件物品')}</div>`}
function ruleView(){return `${pageHead('04 / Better together','一起住，也有共同的约定。','把边界说清，把体谅留下。我们的家，我们共同决定。',`<button class="primary-btn" data-action="add-rule">${icon('plus')} 新建公约</button>`)}<div class="rule-grid">${state.rules.map((x,i)=>{const ok=x.confirmed.includes(state.currentUser);return `<article class="card rule-card" data-entry-id="${x.id}"><div class="item-card-top"><span class="rule-number">${picture(x.iconId)} Agreement ${String(i+1).padStart(2,'0')}</span><span class="tag">${esc(x.category)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.content)}</p><div class="rule-signatures"><div class="avatar-group">${x.confirmed.map(id=>avatar(id)).join('')}</div><span>${x.confirmed.length} / ${state.people.length} 位室友已确认</span></div><div class="progress"><i style="width:${x.confirmed.length/state.people.length*100}%"></i></div><div class="item-card-actions"><button class="${ok?'secondary-btn':'primary-btn'}" data-action="confirm-rule" data-id="${x.id}" ${ok?'disabled':''}>${ok?'✓ 我已确认':'我同意这条约定'}</button><button class="mini-btn" data-action="edit-rule" data-id="${x.id}">编辑公约</button></div>${authorship(x,'rules')}</article>`}).join('')||emptyState('默契，从第一条约定开始','一起说清边界与期待。','add-rule','新建公约')}</div>`}
